### ISSUE TITLE
Problems on RTX 5000 series

### ISSUE THREAD

**Issue by balcieren** [IgorAherne/trellis-stable-projectorz#49]
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by IgorAherne** [comment]
This is related to spconv. I tried to compile it for 5000 but seems something is failing.
https://github.com/IgorAherne/spconv
A detailed readme is included there but it will likely give the same error in the end if you compile it manually.
spconv/cumm doesn't seem to be ready for rtx 5000 yet

**Comment by Rohankumar96506** [comment]
It is working on 5000 series after install this package "pip install spconv-cu120".

**Comment by balcieren** [comment]
> It is working on 5000 series after installing this package "pip install spconv-cu120".

I will try, thanks

**Comment by Maricha883** [comment]
> It is working on 5000 series after installing this package "pip install spconv-cu120".

I put it inside the install.py, but it still doesn't work.
```python
packages_cuda128 = [
            ("pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128", "Installing PyTorch with CUDA 12.8"),
            ("pip install -r requirements.txt", "Installing basic dependencies"),
            ("pip install spconv-cu120", "Installing spconv-cu120"),
            ("pip install -U xformers --index-url https://download.pytorch.org/whl/cu128", "Installing xFormers"),
            ("pip install huggingface_hub", "Installing huggingface_hub"),
            ("pip install git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8", "Installing utils3d"),
        ]
```

**Comment by godsonjoseph** [comment]
@Maricha883 The code uses a file named `trellis_init_done.txt` to detect if it needs to install the dependencies. Since you had already ran the program this file would be present under the folder `code`. Just delete this file and run it again, it should install the dependencies again. It worked for me.

**Comment by IgorAherne** [comment]
fixed with the latest v40 release https://github.com/IgorAherne/trellis-stable-projectorz/releases/tag/latest
